spring:
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=n_plus_one_demo_db;loginTimeout=30;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Server2017ForTests
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org.springframework.web: DEBUG
    com.coox: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernatetype: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE